# Generated by Django 5.0.6 on 2024-05-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('question', models.TextField(default='')),
                ('answer', models.TextField(default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
