# Generated by Django 5.0.6 on 2024-10-29 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConfiguration',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.TextField(max_length=200)),
                ('instruction', models.TextField()),
                ('model_type', models.TextField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='user_id',
            field=models.TextField(default=None, max_length=200),
        ),
    ]
